[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "bevy-template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
hot-lib-reloader = "^0.6"
lib = { path = "./lib" }

[features]
dev = []
