[package]
name = "bevy-template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
space_editor = "0.3.1"

[patch.crates-io]
bevy-inspector-egui = { git = "https://github.com/naomijub/bevy-inspector-egui.git" }
